/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LayananStatus = IDL.Variant({
  'aktif' : IDL.Null,
  'tidakAktif' : IDL.Null,
});
export const Layanan = IDL.Record({
  'id' : IDL.Nat,
  'status' : LayananStatus,
  'clientId' : IDL.Principal,
  'name' : IDL.Text,
  'unitBalance' : IDL.Nat,
  'hargaPerUnit' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'open' : IDL.Null,
  'selesai' : IDL.Null,
  'inProgress' : IDL.Null,
  'memintaReview' : IDL.Null,
});
export const TaskRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'clientId' : IDL.Principal,
  'tipeLayanan' : IDL.Text,
  'gdrive_client' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'deadline' : IDL.Int,
  'detailTask' : IDL.Text,
  'partnerId' : IDL.Opt(IDL.Principal),
  'gdrive_internal' : IDL.Opt(IDL.Text),
  'judulTask' : IDL.Text,
});
export const Delegation = IDL.Record({
  'status' : IDL.Text,
  'assignedBy' : IDL.Principal,
  'createdAt' : IDL.Int,
  'deadline' : IDL.Int,
  'unitLayananTerpakai' : IDL.Nat,
  'partnerId' : IDL.Principal,
  'updatedAt' : IDL.Int,
  'taskId' : IDL.Text,
  'delegationId' : IDL.Nat,
  'jamEfektifPengerjaan' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'status' : IDL.Text,
  'nama' : IDL.Text,
  'role' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'idUser' : IDL.Text,
});
export const UnitTopUp = IDL.Record({
  'clientId' : IDL.Principal,
  'approvedBy' : IDL.Principal,
  'totalCost' : IDL.Nat,
  'pricePerUnit' : IDL.Nat,
  'unitsAdded' : IDL.Nat,
  'timestamp' : IDL.Int,
  'layananId' : IDL.Nat,
  'topUpId' : IDL.Nat,
});
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'adminfinance' : IDL.Null,
  'concierge' : IDL.Null,
  'adminuser' : IDL.Null,
  'guest' : IDL.Null,
  'asistenmu' : IDL.Null,
  'partner' : IDL.Null,
});
export const RegisterUserResponse = IDL.Record({
  'ok' : IDL.Bool,
  'message' : IDL.Text,
  'idUser' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateLayanan' : IDL.Func([IDL.Nat], [Layanan], []),
  'approveUser' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTaskToPartner' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Nat, IDL.Principal],
      [TaskRecord],
      [],
    ),
  'claimAdmin' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'completeTask' : IDL.Func([IDL.Text], [TaskRecord], []),
  'createDelegation' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Int, IDL.Nat, IDL.Nat],
      [Delegation],
      [],
    ),
  'createLayanan' : IDL.Func([IDL.Text, IDL.Principal, IDL.Nat], [Layanan], []),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [TaskRecord],
      [],
    ),
  'getActiveAsistenmu' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getActiveClients' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getActiveInternalStaff' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getActiveLayanan' : IDL.Func([IDL.Nat], [IDL.Vec(Layanan)], ['query']),
  'getActivePartners' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllDelegations' : IDL.Func([], [IDL.Vec(Delegation)], ['query']),
  'getAllLayanan' : IDL.Func([], [IDL.Vec(Layanan)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
  'getAllTopUps' : IDL.Func([], [IDL.Vec(UnitTopUp)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAsistenmuCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getClientTopUps' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(UnitTopUp)],
      ['query'],
    ),
  'getInternalStaffCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyDelegationsAsPartner' : IDL.Func([], [IDL.Vec(Delegation)], ['query']),
  'getMyLayanan' : IDL.Func([], [IDL.Vec(Layanan)], ['query']),
  'getMyTasksAsClient' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
  'getMyTasksAsPartner' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
  'getPaginatedLayanan' : IDL.Func([IDL.Nat], [IDL.Vec(Layanan)], ['query']),
  'getPartnerActiveEffectiveHours' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat],
      ['query'],
    ),
  'getPartnerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserByPrincipal' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'status' : IDL.Text,
            'nama' : IDL.Text,
            'role' : IDL.Text,
            'idUser' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'partnerRequestsReview' : IDL.Func([IDL.Text], [TaskRecord], []),
  'redelegateTask' : IDL.Func([IDL.Nat, IDL.Principal], [TaskRecord], []),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Role,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [RegisterUserResponse],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func(
      [UserProfile],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'searchPartners' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'topUpUnits' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LayananStatus = IDL.Variant({
    'aktif' : IDL.Null,
    'tidakAktif' : IDL.Null,
  });
  const Layanan = IDL.Record({
    'id' : IDL.Nat,
    'status' : LayananStatus,
    'clientId' : IDL.Principal,
    'name' : IDL.Text,
    'unitBalance' : IDL.Nat,
    'hargaPerUnit' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'open' : IDL.Null,
    'selesai' : IDL.Null,
    'inProgress' : IDL.Null,
    'memintaReview' : IDL.Null,
  });
  const TaskRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'clientId' : IDL.Principal,
    'tipeLayanan' : IDL.Text,
    'gdrive_client' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'deadline' : IDL.Int,
    'detailTask' : IDL.Text,
    'partnerId' : IDL.Opt(IDL.Principal),
    'gdrive_internal' : IDL.Opt(IDL.Text),
    'judulTask' : IDL.Text,
  });
  const Delegation = IDL.Record({
    'status' : IDL.Text,
    'assignedBy' : IDL.Principal,
    'createdAt' : IDL.Int,
    'deadline' : IDL.Int,
    'unitLayananTerpakai' : IDL.Nat,
    'partnerId' : IDL.Principal,
    'updatedAt' : IDL.Int,
    'taskId' : IDL.Text,
    'delegationId' : IDL.Nat,
    'jamEfektifPengerjaan' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'status' : IDL.Text,
    'nama' : IDL.Text,
    'role' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'idUser' : IDL.Text,
  });
  const UnitTopUp = IDL.Record({
    'clientId' : IDL.Principal,
    'approvedBy' : IDL.Principal,
    'totalCost' : IDL.Nat,
    'pricePerUnit' : IDL.Nat,
    'unitsAdded' : IDL.Nat,
    'timestamp' : IDL.Int,
    'layananId' : IDL.Nat,
    'topUpId' : IDL.Nat,
  });
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'adminfinance' : IDL.Null,
    'concierge' : IDL.Null,
    'adminuser' : IDL.Null,
    'guest' : IDL.Null,
    'asistenmu' : IDL.Null,
    'partner' : IDL.Null,
  });
  const RegisterUserResponse = IDL.Record({
    'ok' : IDL.Bool,
    'message' : IDL.Text,
    'idUser' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateLayanan' : IDL.Func([IDL.Nat], [Layanan], []),
    'approveUser' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTaskToPartner' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat, IDL.Principal],
        [TaskRecord],
        [],
      ),
    'claimAdmin' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'completeTask' : IDL.Func([IDL.Text], [TaskRecord], []),
    'createDelegation' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Int, IDL.Nat, IDL.Nat],
        [Delegation],
        [],
      ),
    'createLayanan' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat],
        [Layanan],
        [],
      ),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [TaskRecord],
        [],
      ),
    'getActiveAsistenmu' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getActiveClients' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getActiveInternalStaff' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getActiveLayanan' : IDL.Func([IDL.Nat], [IDL.Vec(Layanan)], ['query']),
    'getActivePartners' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllDelegations' : IDL.Func([], [IDL.Vec(Delegation)], ['query']),
    'getAllLayanan' : IDL.Func([], [IDL.Vec(Layanan)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
    'getAllTopUps' : IDL.Func([], [IDL.Vec(UnitTopUp)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAsistenmuCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getClientTopUps' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(UnitTopUp)],
        ['query'],
      ),
    'getInternalStaffCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyDelegationsAsPartner' : IDL.Func(
        [],
        [IDL.Vec(Delegation)],
        ['query'],
      ),
    'getMyLayanan' : IDL.Func([], [IDL.Vec(Layanan)], ['query']),
    'getMyTasksAsClient' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
    'getMyTasksAsPartner' : IDL.Func([], [IDL.Vec(TaskRecord)], ['query']),
    'getPaginatedLayanan' : IDL.Func([IDL.Nat], [IDL.Vec(Layanan)], ['query']),
    'getPartnerActiveEffectiveHours' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getPartnerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserByPrincipal' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'status' : IDL.Text,
              'nama' : IDL.Text,
              'role' : IDL.Text,
              'idUser' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'partnerRequestsReview' : IDL.Func([IDL.Text], [TaskRecord], []),
    'redelegateTask' : IDL.Func([IDL.Nat, IDL.Principal], [TaskRecord], []),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Role,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [RegisterUserResponse],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfile],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'searchPartners' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'topUpUnits' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };