/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Layanan {
  'id' : bigint,
  'status' : LayananStatus,
  'clientId' : Principal,
  'name' : string,
}
export type LayananStatus = { 'aktif' : null } |
  { 'tidakAktif' : null };
export interface RegisterUserResponse {
  'ok' : boolean,
  'message' : string,
  'idUser' : string,
}
export type Role = { 'client' : null } |
  { 'admin' : null } |
  { 'adminfinance' : null } |
  { 'concierge' : null } |
  { 'adminuser' : null } |
  { 'guest' : null } |
  { 'asistenmu' : null } |
  { 'partner' : null };
export interface Task {
  'id' : string,
  'tipeLayanan' : string,
  'createdAt' : bigint,
  'deadline' : bigint,
  'detailTask' : string,
  'judulTask' : string,
}
export interface UserProfile {
  'status' : string,
  'nama' : string,
  'role' : string,
  'whatsapp' : string,
  'email' : string,
  'idUser' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], { 'ok' : boolean, 'message' : string }>,
  'createLayanan' : ActorMethod<[string, Principal], Layanan>,
  'createTask' : ActorMethod<[string, string, string, bigint], Task>,
  'getAllLayanan' : ActorMethod<[], Array<Layanan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyLayanan' : ActorMethod<[], Array<Layanan>>,
  'getUserByPrincipal' : ActorMethod<
    [string],
    [] | [
      { 'status' : string, 'nama' : string, 'role' : string, 'idUser' : string }
    ]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[], [] | [Role]>,
  'isAdminClaimed' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, string, string, string, Role, [] | [string], [] | [string]],
    RegisterUserResponse
  >,
  'saveCallerUserProfile' : ActorMethod<
    [UserProfile],
    { 'ok' : boolean, 'message' : string }
  >,
  'updateLayananStatus' : ActorMethod<[bigint, LayananStatus], Layanan>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];